### PR TITLE
fix(simple-storage/device): add device name

### PR DESCRIPTION
**Pull request by mahuihuang**
Add a name field to distinguish between devices.

### CODE REVIEW

**Review by stmcginnis — APPROVED** [review]
Thanks, looks good.

**Comment by stmcginnis** [comment]
Looks like I need to update the linter rules. Failure is not related to this change.

**Comment by mahuihuang** [comment]
Excuse me, when will the next stable version be released? I have a project that uses this dependency.

**Comment by stmcginnis** [comment]
You can always reference by sha in your `go.mod`, but I can tag an actual release if that makes it easier.

**Comment by stmcginnis** [comment]
Published: https://github.com/stmcginnis/gofish/releases/tag/v0.13.0

**Comment by mahuihuang** [comment]
Thank you for your reply

**Pull request merged**
