### PR TITLE
Avoid nil pointer dereference with errors on Delete

### PR DESCRIPTION
**Pull request by treydock**
Full trace below. The exporter function that triggered was `Logout()`.
```
Jan 29 11:22:10 prometheus01 redfish_exporter: panic: runtime error: invalid memory address or nil pointer dereference
Jan 29 11:22:10 prometheus01 redfish_exporter: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x844128]
Jan 29 11:22:10 prometheus01 redfish_exporter: goroutine 1570670 [running]:
Jan 29 11:22:10 prometheus01 redfish_exporter: github.com/stmcginnis/gofish.(*APIClient).Delete(0xc006823f40, 0xc00af972a0, 0x19, 0x872724, 0xc002731d78)
Jan 29 11:22:10 prometheus01 redfish_exporter: /users/sysp/tdockendorf/go/pkg/mod/github.com/treydock/gofish@v0.2.1-0.20200129132656-cfef2fbfcc83/client.go:171 +0x68
Jan 29 11:22:10 prometheus01 redfish_exporter: github.com/stmcginnis/gofish/redfish.DeleteSession(...)
Jan 29 11:22:10 prometheus01 redfish_exporter: /users/sysp/tdockendorf/go/pkg/mod/github.com/treydock/gofish@v0.2.1-0.20200129132656-cfef2fbfcc83/redfish/session.go:103
Jan 29 11:22:10 prometheus01 redfish_exporter: github.com/stmcginnis/gofish.(*Service).DeleteSession(...)
Jan 29 11:22:10 prometheus01 redfish_exporter: /users/sysp/tdockendorf/go/pkg/mod/github.com/treydock/gofish@v0.2.1-0.20200129132656-cfef2fbfcc83/serviceroot.go:267
Jan 29 11:22:10 prometheus01 redfish_exporter: github.com/stmcginnis/gofish.(*APIClient).Logout(0xc006823f40)
Jan 29 11:22:10 prometheus01 redfish_exporter: /users/sysp/tdockendorf/go/pkg/mod/github.com/treydock/gofish@v0.2.1-0.20200129132656-cfef2fbfcc83/client.go:264 +0x62
Jan 29 11:22:10 prometheus01 redfish_exporter: github.com/jenningsloy318/redfish_exporter/collector.(*RedfishCollector).Collect(0xc00add1e60, 0xc006befbc0)
Jan 29 11:22:10 prometheus01 redfish_exporter: /users/sysp/tdockendorf/git/redfish_exporter/collector/redfish_collector.go:99 +0x365
Jan 29 11:22:10 prometheus01 redfish_exporter: github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
Jan 29 11:22:10 prometheus01 redfish_exporter: /users/sysp/tdockendorf/go/pkg/mod/github.com/prometheus/client_golang@v1.1.0/prometheus/registry.go:442 +0x19d
Jan 29 11:22:10 prometheus01 redfish_exporter: created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
Jan 29 11:22:10 prometheus01 redfish_exporter: /users/sysp/tdockendorf/go/pkg/mod/github.com/prometheus/client_golang@v1.1.0/prometheus/registry.go:453 +0x57d
```

### CODE REVIEW

**Comment by stmcginnis** [comment]
Hmm, I can't see where this would fix that issue. Was this reproducible for you to the point that you were able to validate that this fixed it?

**Comment by treydock** [comment]
I have the prometheus exporter hitting 1500 systems every few minutes via redfish and only hit this once every now and then, was not very frequent and appears to be when Redfish logout returned an error I think. I've added this PR to my deployed builds and seen no issues.

My read of the code is that upon error the response returned is `nil` so doing `resp.Body` would be operating on something with `nil` value so then doing `resp.Body.Close()` will fail.

**Comment by stmcginnis** [comment]
OK, I think I see how that could happen then. Can you change this to be:

if resp.body != nil {
    resp.body.close()
}

**Comment by treydock** [comment]
Change updated

**Comment by treydock** [comment]
Modified slightly, because on errors `resp` will be `nil` so `resp.Body` will also cause issues. I am only a few weeks into Go but if Go is like other languages then the first item in condition will stop second.

**Comment by stmcginnis** [comment]
Hah, now I see that it was likely good due to being after the err check and return. Note to self: don’t review code while traveling. ;)

Thanks for the update. This is probably much safer this way. Great to hear it’s working well now for the scale that you are using it!

**Pull request merged**
