### PR TITLE
feat: support oem field of thermal and fan

### PR DESCRIPTION
**Pull request by daadajuan**

### CODE REVIEW

**Review by stmcginnis — COMMENTED** [review]
Sorry for the delay checking this out. This looks great! Thanks for working on it.

There are a few issues that the linter job caught (`make lint`). If you can address those, then I think this is good to go.

Thanks!

**Comment by stmcginnis** [comment]
Hi @daadajuan - will you be able to update this to address the lint issues?

**Comment by daadajuan** [comment]
@stmcginnis Sorry for the late, I have resolved the lint issues, please check it, thanks a lot.

**Review by stmcginnis — APPROVED** [review]
Thanks @daadajuan!!

**Pull request merged**
