### PR TITLE
Add *http.Response return to APIClient.Delete method

### PR DESCRIPTION
**Pull request by mikeletux**
Hello Sean,

I'm proposing the PR in reference to [!82](https://github.com/stmcginnis/gofish/issues/85).

I've little tested the new APIClient.Delete call and it works. I also needed to change some other files that used that call. I've always followed the philosophy of being as less intrusive in the code as possible. 

Now the Client interface looks like this (please check the **Delete** definition):
~~~
type Client interface {
	Get(url string) (*http.Response, error)
	Post(url string, payload interface{}) (*http.Response, error)
	Patch(url string, payload interface{}) (*http.Response, error)
	Put(url string, payload interface{}) (*http.Response, error)
	Delete(url string) (*http.Response, error)
}
~~~

Files also changed apart from client.go and types.go:
- eventdestination.go
- session.go

Thanks!
/Miguel

### CODE REVIEW

**Comment by mikeletux** [comment]
As far as I know the CI pipeline fails because of the tests not being able to use the new signature.
Should we modify the Mocked client and rest of tests?

**Comment by stmcginnis** [comment]
Yeah, I think things should pass once you update the mocked client. That needs to track the real client.

**Comment by mikeletux** [comment]
yeah, I think so 😄 
I will push an update, hopefully this weekend solving that

**Comment by mikeletux** [comment]
Hello Sean,

I've done the changes needed to the mock client as well as the needed dependencies.

Let me know.
Best regards.
/Miguel

**Comment by stmcginnis** [comment]
Thanks @mikeletux, looks great!

**Pull request merged**
